In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.metrics import (r2_score, 
                             mean_squared_error, 
                             mean_absolute_error, 
                             mean_absolute_percentage_error)

from tqdm.auto import tqdm

np.random.seed(12345)

# ========== Data ==========

In [2]:
data = pd.read_csv('dataset.csv')

In [3]:
data

x1  x2   y
0    2   1   9
1    2  -1   1
2   -2   2   6
3    1   2  11
4   -2   3   9
5    2   0   5
6   -1  -1  -2
7   -2   1   3
8    0   0   2
9    1  -1   0
10  -1   0   1
11  -1   1   4
12   1   3  15
13   2   2  13
14   2   3  17
15   1   1   7
16   0   2   9
17  -1   3  11

In [4]:
X = data[['x1', 'x2']]

In [5]:
y = data['y']

In [6]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, shuffle=True)

# ========== Model ==========

In [7]:
best_mse = np.inf

alphas = np.logspace(-3, 2, 100)

for alpha in tqdm(alphas):
    reg = MLPRegressor(
        hidden_layer_sizes=(5, 4),
        activation='relu',
        solver='sgd',
        alpha=alpha,
        learning_rate_init=0.01,
        max_iter=4000,
        momentum=0,
    )

    reg.fit(X_train, y_train)    
    y_pred_val = reg.predict(X_val)
    mse = mean_squared_error(y_val, y_pred_val)
    
    if mse < best_mse:
        best_mse = mse
        best_reg = reg

  0%|          | 0/100 [00:00<?, ?it/s]

In [8]:
best_reg.alpha

0.23644894126454072

In [9]:
best_reg.intercepts_

[array([ 0.7410722 ,  0.76853187,  0.88792032, -0.43691839, -0.65697003]),
 array([ 0.23749952,  0.37873984, -0.51860603,  0.38609425]),
 array([-0.27207379])]

In [10]:
best_reg.coefs_

[array([[-0.23933438,  0.23355321,  0.53761298, -0.7461245 ,  0.81161848],
        [ 0.98052388,  0.49955697,  0.94311019, -0.67837815,  0.86250313]]),
 array([[ 0.62081099, -0.63102767,  0.5869792 , -0.13497331],
        [ 0.05241102,  0.35767277,  0.76417819,  0.14691354],
        [ 0.22558177, -0.10670296,  1.00671161,  0.2870868 ],
        [ 0.61015244,  0.93573014,  0.49795074, -0.58902725],
        [-0.2892097 , -0.30257028,  0.90879741,  0.1335278 ]]),
 array([[ 0.01094408],
        [-0.93727487],
        [ 1.44748687],
        [ 0.26317839]])]

# ========== Prediction ==========

In [11]:
X = pd.read_csv('incoming_data.csv')

In [12]:
best_reg.predict(X)

array([13.00952749, -1.28810546,  5.03517769, -0.85005027])